version: '3.9'

services:
  nestjs_api:
    # image: nestjs-docker
    build:
      context: .
      dockerfile: Dockerfile
      # mapping from the host port to the container port
    ports:
      - "7000:7000 " 
    environment:
     - PORT: 7000
     - NODE_ENV: development
    volumes:
      - ./src/usr/src/app/src

  postgres_db:
     image: postgres
     ports:  
       - "5432:5432"
     environment:
      #  - POSTGRES_ROOT_PASSWORD=postgres
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
      #  - POSTGRES_TCP_PORT=5432

# version: "3.9"

# services:
#   postgres:
#     image: postgres:12
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - data:/var/lib/postgresql/data

#   pg-admin:
#     image: dpage/pgadmin4:6
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@email.com
#       - PGADMIN_DEFAULT_PASSWORD=admin
#       - PGADMIN_LISTEN_PORT=5050

#     ports:
#       - "5050:5050"

# volumes:
#   data: