version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=formula10
            - POSTGRES_DB=management
        ports: 
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
    pgadmin:
        image: dpage/pgadmin4:latest
        environment: 
            - PGADMIN_DEFAULT_EMAIL=mercydanke@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=formula10
        ports: 
            - "5050:80"